services:
  webserver:
    container_name: "${COMPOSE_PROJECT_NAME}-webserver"
    image: "skodak2/mdc-php-apache:${MDC_PHP_VERSION}"
    depends_on:
      - db
    volumes:
      - "${MDC_DIRROOT}:/var/www/html"
      - "${MDC_BASEDIR}/assets/webserver/apache2_deny.conf:/etc/apache2/conf-enabled/apache2_deny.conf:ro"
      - "${MDC_BASEDIR}/assets/webserver/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf:ro"
      - "${MDC_BASEDIR}/assets/webserver/config-moodle.php:/var/www/config-moodle.php:ro"
      - "${MDC_BASEDIR}/assets/webserver/php_wrapper:/mdc/php_wrapper:ro"
      - "${MDC_BASEDIR}/assets/webserver/php-debug:/usr/local/bin/php-debug:ro"
      - "${MDC_BASEDIR}/assets/webserver/nvm_install.sh:/mdc/nvm_install.sh:ro"
      - "${MDC_BASEDIR}/assets/webserver/npm_install.sh:/mdc/npm_install.sh:ro"
      - "${MDC_BASEDIR}/assets/webserver/ngrok-init.sh:/mdc/ngrok-init.sh:ro"
      - "${MDC_BASEDIR}/assets/webserver/ngrok-start.sh:/mdc/ngrok-start.sh:ro"
      - "${MDC_BACKUP_PATH}:/var/backups"
      - "${MDC_BASEDIR}/assets/webserver/mdc-backup.sh:/mdc/mdc-backup.sh:ro"
      - "${MDC_BASEDIR}/assets/webserver/mdc-restore.sh:/mdc/mdc-restore.sh:ro"
    environment:
      MDC_RUNNING: 1
      MDC_DB_TYPE: "${MDC_DB_TYPE}"
      MDC_DB_VERSION: "${MDC_DB_VERSION}"
      MDC_DB_COLLATION: "${MDC_DB_COLLATION:-}"
      MDC_DBNAME: moodle
      MDC_DBUSER: moodle
      MDC_DBPASS: "m@0dl3ing"
      MDC_BEHAT_BROWSER: "${MDC_BEHAT_BROWSER}"
      MDC_BEHAT_BROWSER_HEADLESS: "${MDC_BEHAT_BROWSER_HEADLESS:-}"
      COMPOSE_PROJECT_NAME:  "${COMPOSE_PROJECT_NAME}"
      COMPOSER_ALLOW_SUPERUSER: 1
