services:
  webserver:
      environment:
        MDC_PHPUNIT_EXTRAS: "true"
  memcached0:
    container_name: "${COMPOSE_PROJECT_NAME}-memcached0"
    image: memcached:1.6
  memcached1:
    container_name: "${COMPOSE_PROJECT_NAME}-memcached1"
    image: memcached:1.6
  mongo:
    container_name: "${COMPOSE_PROJECT_NAME}-mongo"
    image: mongo:4.0
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis:5
  solr:
    container_name: "${COMPOSE_PROJECT_NAME}-solr"
    image: solr:6.5
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test
  ldap:
    container_name: "${COMPOSE_PROJECT_NAME}-ldap"
    image: osixia/openldap:1.5.0
